name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: baking-bread/flows/.github/workflows/golang-test.yaml@main
    with:
      golang_version: "1.22.2"
  scan:
    uses: baking-bread/flows/.github/workflows/golang-scan.yaml@main
    with:
      golang_version: "1.22.2"
  build:
    uses: baking-bread/flows/.github/workflows/golang-build.yaml@main
    with:
      golang_version: "1.22.2"
      executable_name: "taxonomist"
  release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    uses: baking-bread/flows/.github/workflows/golang-release.yaml@main
    with:
      golang_version: "1.22.2"
      artifact_run_id: ${{ github.job.build.outputs.workflow_run_id }}
