name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

      - name: Install dependencies
        run: go mod download

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "cyclonedx"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          output: "bin/sbom.cdx.json"

      - name: Lint
        run: |
          go vet ./...
          golangci-lint run

      - name: Test
        run: |
          go test -v ./... -coverprofile=coverage.out
          go tool cover -func=coverage.out

      - name: Build
        run: |
          go build -o bin/taxonomist main.go
          cd bin && sha256sum taxonomist > taxonomist.sha256

      - name: Upload binary and security files
        uses: actions/upload-artifact@v4
        with:
          name: taxonomist
          path: |
            bin/taxonomist
            bin/taxonomist.sha256
            bin/sbom.cdx.json

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -o bin/taxonomist main.go
